### ISSUE TITLE
::ffff !

### ISSUE THREAD

**Issue by brucelane** [videodromm/netdromm#17]
client address is ::ffff:127.0.0.1
I don't know what this ::ffff: means, maybe we should dump it and only keep the useful ip address?

**Comment by jarpi** [comment]
[IPV6](http://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1) related stuff

**Comment by brucelane** [comment]
good to know!

**Comment by brucelane** [comment]
I think it should just stay as is, in case of real ip v6 addresses coming
